In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Desarrolla una función modelo_aleatorio en el cual:

# a. Se soliciten 4 numeros aleatorios entre el 0 y el 1, a los que llamaremos x1, y1, x2, y2.

# b. Se obtenga el valor de os pesos de la recta que pasa entre los dos puntos calculados como:  k_2 = 1 k_1 = (y2 - y1) / (x2 - x1) 
# k_0 = y_1 - k_1 * x_1 

# de forma que:

# k_0, k_1, k_2 = modelo_aleatorio()
def modelo_aleatorio():
    r = np.random.random_sample(4)
    x1, y1, x2, y2 = r[0], r[1], r[2], r[3]
    k_2 = 1
    k_1 =(y2-y1)/(x2-x1)
    k_0 = y1 - k_1 * x1
    return k_0, k_1, k_2
print (modelo_aleatorio())

(-0.76629293009192689, 3.48155198409389, 1)


In [5]:
# Desarrolla una función genera_datostal que reciba un número entero positivo N y devuelva una matriz X de Nrenglones y 
# 2 columnas de manera que los valores de la matriz sean datos aleatorios en el intervalo [0, 1].
def genera_datos(N):
    c = np.ones((N,1))
    a = np.random.rand(N,2)
    X = np.c_[c, a]
    return X
print (genera_datos(10))
    

[[ 1.          0.90061247  0.3979631 ]
 [ 1.          0.30208226  0.30119088]
 [ 1.          0.45389267  0.58340129]
 [ 1.          0.30486378  0.85477468]
 [ 1.          0.17183726  0.99777636]
 [ 1.          0.82340714  0.63971118]
 [ 1.          0.29126501  0.98212915]
 [ 1.          0.65465993  0.86848511]
 [ 1.          0.59681576  0.7515553 ]
 [ 1.          0.14079459  0.35074478]]


In [9]:
# Desarrolla una función discriminante_lineal tal que reciba tres valores k_0 k_1 y k_2 y una matriz X de 2 por N 
# y devuelva un vector Y de N elementos tales que por cada renglon j de la matriz X, se devuelva el j-ésimo valor del 
# vector Y tal que su valor sea sign(k_0 + k_1 * x_1 + k_2 * x_2).

def discriminate_lineal(k_0,k_1,k_2,X):
    Y = []
    j = 0
    for i in X: Y.append(np.sign(k_0 + k_1 * i[0] + k_2 * i[1]))
    return Y

k_0, k_1, k_2 = modelo_aleatorio()
X = genera_datos(25)
Y = discriminate_lineal(k_0, k_1, k_2 ,X)
print (Y)

[1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0]


In [5]:
# Desarrolla una función PLA que implemente el algoritmo de aprendizaje del perceptrón para encontrar w_0, w_1 y w_2.
# w_0, w_1, w_2 = PLA(X, Y)



In [6]:
k_0, k_1, k_2 = modelo_aleatorio()
X = genera_datos(25)
Y = discriminate_lineal(k_0, k_1, k_2 ,X)
a,b,c = PLA(X,Y)
print(a,b,c)

ValueError: a must be 1-dimensional