In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Desarrolla una función modelo_aleatorio en el cual:

# a. Se soliciten 4 numeros aleatorios entre el 0 y el 1, a los que llamaremos x1, y1, x2, y2.

# b. Se obtenga el valor de os pesos de la recta que pasa entre los dos puntos calculados como:  k_2 = 1 k_1 = (y2 - y1) / (x2 - x1) 
# k_0 = y_1 - k_1 * x_1 

# de forma que:

# k_0, k_1, k_2 = modelo_aleatorio()
def modelo_aleatorio():
    r = np.random.random_sample(4)
    x1, y1, x2, y2 = r[0], r[1], r[2], r[3]
    k_2 = 1
    k_1 =(y2-y1)/(x2-x1)
    k_0 = y1 - k_1 * x1
    return k_0, k_1, k_2
print (modelo_aleatorio())

(0.82472185270288212, -1.6571103508569311, 1)


In [3]:
# Desarrolla una función genera_datostal que reciba un número entero positivo N y devuelva una matriz X de Nrenglones y 
# 2 columnas de manera que los valores de la matriz sean datos aleatorios en el intervalo [0, 1].
def genera_datos(N):
    c = np.ones((N,1))
    a = np.random.rand(N,2)
    X = np.c_[c, a]
    return X
print (genera_datos(10))
    

[[ 1.          0.87156435  0.18238486]
 [ 1.          0.98902142  0.44559538]
 [ 1.          0.5697359   0.96819413]
 [ 1.          0.86637066  0.57912101]
 [ 1.          0.1328381   0.84365537]
 [ 1.          0.67556005  0.19298139]
 [ 1.          0.83936031  0.52499339]
 [ 1.          0.87626397  0.72241549]
 [ 1.          0.06206809  0.20850383]
 [ 1.          0.92472518  0.22565661]]


In [41]:
# Desarrolla una función discriminante_lineal tal que reciba tres valores k_0 k_1 y k_2 y una matriz X de 2 por N 
# y devuelva un vector Y de N elementos tales que por cada renglon j de la matriz X, se devuelva el j-ésimo valor del 
# vector Y tal que su valor sea sign(k_0 + k_1 * x_1 + k_2 * x_2).

def discriminate_lineal(k_0,k_1,k_2,X):
    Y = []
    for i in X: Y.append(np.sign(k_0 + k_1 * i[1] + k_2 * i[2]))
    return Y

k_0, k_1, k_2 = modelo_aleatorio()
X = genera_datos(25)
Y = discriminate_lineal(k_0, k_1, k_2 ,X)
print (Y)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [44]:
# Desarrolla una función PLA que implemente el algoritmo de aprendizaje del perceptrón para encontrar w_0, w_1 y w_2.
# w_0, w_1, w_2 = PLA(X, Y)

def PLA(X,Y):
    max_iter = 0
    w = np.random.uniform(0, 1, size=X.shape[1])
    Y_est = np.sign(np.dot(X, w)) 
    error = Y_est * Y
    while any(e > 0 for e in error) and max_iter < 1000:
        i = np.random.choice(X.shape[0])
        sign = np.sign(np.dot(X[i], w))

        if sign == Y[i]:
            pass
        else:
            w = w + np.dot(X[i], Y[i])
            Y_est = np.sign(np.dot(X, w)) 
            error = Y_est * Y

        max_iter += 1

    return w
        
  

In [46]:
k_0, k_1, k_2 = modelo_aleatorio()
X = genera_datos(25)
Y = discriminate_lineal(k_0, k_1, k_2 ,X)
a,b,c = PLA(X,Y)
print(a,b,c)

0.327377319446 0.108838297223 0.912692451932


In [7]:
# Desarrolla una función error_clasificacion que reciba un vector de valores Yy un vector de valores Y_e y calcule el porcentaje 
# de valores diferentes entre ambos vectores
#  e = error_clasificacion(Y, Y_e)

def error_clasificacion(Y, Y_e):
    errores = 0
    for i,j in zip(Y,Y_e):
         if i != j: errores += 1
    return errores/len(Y)

In [8]:
E = error_clasificacion(Y,Y)
print(E)

0.0


In [9]:
# Prueba que el conjunto funciona, esto es, para diferentes valores de N y repetidos tantas veces como sea necesario al realizar lo siguiente:
#  k_0, k_1, k_2 = modelo_aleatorio()
#  X = genera_datos(N)
#  Y = discriminante_lineal(k_0, k_1, k_2, X)
#  w_0, w_1, w_2 = PLA(X, Y)
#  Y_e = discriminante_lineal(w_0, w_1, w_2, X)
#  E_i = error_clasificacion(Y, Y_e)
# en todos los casos e debe de ser 0 o un valor muy cercano (como 1e-12).

k_0, k_1, k_2 = modelo_aleatorio()
X = genera_datos(100)
Y = discriminate_lineal(k_0, k_1 , k_2, X)
w_0, w_1, w_2 = PLA(X, Y)
Y_e = discriminate_lineal(w_0, w_1, w_2, X)
E_i = error_clasificacion(Y, Y_e)

print(Y,E_i)


[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 0.0


In [10]:
# E_i Es en este caso el error en muestra, que es el que se obtiene de verificar el error que el clasificador 
# (descrito por w_0, w_1 y w_2) presenta respecto a los datos reales, pero únicamente de datos de aprendizaje.
# 
# Este error no es exactamente el error fuera de muestra, y para calcular dicho error en el plano [0, 1] x [0, 1] 
# hay que realizar algunas operaciones de geometría analítica que no siempre son sencillas. Por esta razón vamos a 
# considerar estimar el E_out, con un conjunto de datos sensiblemente mayor al que utilizamos para el aprendizaje.
# por ejemplo:

X_o = genera_datos(10000)
Y_o = discriminate_lineal(k_0, k_1, k_2, X_o)
Y_eo = discriminate_lineal(w_0, w_1, w_2, X_o)
E_o = error_clasificacion(Y_o, Y_eo)
print(E_o)

0.0


In [48]:
# Ahora vamos a comparar con un número diferente de datos de aprendizaje, como E_o cambia en terminos generales.
# Con el fin de generalizar, haga una función que reciba un valor N y devuelva un E_o_prom estimado de la siguiente forma:

def Eout_prom(N):
    E_lista = np.zeros(500)
    X_o = genera_datos(10000)
    for epoch in range(1,100):
            k_0, k_1, k_2 = modelo_aleatorio()
            Y_o = discriminate_lineal(k_0, k_1, k_2, X_o)
            for iter in range(1,100):
                X = genera_datos(N)
                Y = discriminate_lineal(k_0, k_1, k_2, X)
                w_0, w_1, w_2 = PLA(X, Y)
                Y_eo = discriminate_lineal(w_0, w_1, w_2, X_o)
                E_o = error_clasificacion(Y_o, Y_eo)
                indice = 100 * epoch + iter

                if len(E_lista) <= indice:
                    temp = np.zeros(indice + 1)
                    for i in range(len(E_lista)):
                        temp[i] = E_lista[i]
                    temp[indice] = E_o
                    E_lista = temp[:]
                else:
                    E_lista[indice] = E_o

    return sum(E_lista) / len(E_lista)
      

In [51]:
E_o_prom = Eout_prom(5)
print(E_o_prom)

0.04951742
