#El algoritmo del perceptrón, y el error en muestra y fuera de muestra

#Introducción

Esta práctica tiene como fin poner en relieve las ideas básicas de el aprendizaje, utilizando uno de los métodos de aprendizaje más antiguos y fáciles de implementar.

Esta práctica no intenta ser un remplazo del curso, por lo que se asume que los estudiantes conocen el algoritmo de aprendizaje del perceptrón (PLA por sus sigles en inglés), así como las ideas básicas sobre error en muestra y error fuera de muestra. Para esta práctica se puede realizar el problema en cualquier lenguaje de computación que conozca el estudiante. Sin embargo, se recomienda un lenguaje con capacidades de graficación, tal como Matlab, R y Python (con numpy y matplotlib).

Recordemos que el error fuera de muestra E_o es el error sobre todo el conjunto de puntos del espacio X. Una vez definido el criterio del error, el objetivo del aprendizaje es encontrar una hipótesis g en el conjunto de todas las hipótesis posibles que se pueden hacer con el método de aprendizaje.

Lamentablemente, en todos los casos reales se desconoce E_o y lo más que se puede esperar es aproximarlo a partir del error en muestra E_i, el cual se define como el error medio de un conjunto de datos de aprendizaje disponibles.

Para el caso del perceptrón, E_o es la esperanza que un dato se encuentre mal clasificado, y E_i es el porcentaje de datos mal clasificados por el perceptrón. Tambien sabemos, por lo visto en el curso, que si el conjunto de datos que se utiliza en el algoritmo de PLA es linealmente separable, entonces siempre se tiene una hipótesis final g tal que E_i = 0.

Entonces, ¿Si E_i = 0, podríamos decir que el PLA aprende perfectamente? Desgraciadamente esto es falso. ¿Y eso porqué? Pues porque lo que nos interesa es E_o = 0 y no E_i = 0. Esta práctica tiene como fin dejar clara la diferencia entre E_i y E_o.

Para esto, vamos a hacer un poco de trampa, vamos a suponer que nosotros efectivamente conocemos la función con la que se generaron los datos de aprendizaje, la cual va a ser una función del tipo y = sign(k_0 + k_1 * x_1 + k_2 * x_2). Después vamos a generar datos con esta función, y vamos a estimar g(x) = sign(w_0 + w_1 * x_1 + w_2 * x_2) con el PLA. Así nosotros podemos hacer una estimación suficientemente aproximada de que tan grande es en general la diferencia entre E_i y E_o para diferente número de datos en el conjunto de aprendizaje.



#Práctica a realizar

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

*   Desarrolla una función `modelo_aleatorio` en el cual:

	a. Se soliciten 4 numeros aleatorios entre el 0 y el 1, a los que llamaremos x1, y1, x2, y2.

	b. Se obtenga el valor de os pesos de la recta que pasa entre los dos puntos calculados como:

        k_2 = 1
        k_1 = (y2 - y1) / (x2 - x1)
        k_0 = y_1 - k_1 * x_1


	de forma que:

        k_0, k_1, k_2 = modelo_aleatorio()

In [6]:
def modelo_aleatorio():

    x1 = np.random.uniform(0,1)
    y1 = np.random.uniform(0,1)
    x2 = np.random.uniform(0,1)
    y2 = np.random.uniform(0,1)

    k_2 = 1.0 
    k_1 = (y2 - y1) / (x2 - x1) 
    k_0 = y1 - k_1 * x1 

    return k_0, k_1, k_2

In [12]:
print "Funcion 1: modelo_aleatorio \n"

k_0, k_1, k_2 = modelo_aleatorio()

print k_0
print k_1
print k_2

Funcion 1: modelo_aleatorio 

0.994439812313
-0.865269703461
1.0


* Desarrolla una función `genera_datos` tal que reciba un número entero positivo `N` y devuelva una matriz `X` 
   de `N` renglones y 2 columnas de manera que los valores de la matriz sean datos aleatorios en el intervalo [0, 1].
   ```
   X = genera_datos(N)
   ```

In [8]:
def genera_datos(N):

    return None if N <= 0 else np.column_stack((np.ones(N), (np.random.uniform(0, 1, size=(N, 2)))))

In [10]:
print "Funcion 2: genera_datos \n"

X = genera_datos(25)

print X

Funcion 2: genera_datos 

[[ 1.          0.74441723  0.40604331]
 [ 1.          0.81857627  0.72836445]
 [ 1.          0.37206644  0.57989478]
 [ 1.          0.90623458  0.98916254]
 [ 1.          0.78177963  0.37712439]
 [ 1.          0.18857896  0.88062409]
 [ 1.          0.33391775  0.43429315]
 [ 1.          0.01982665  0.80542992]
 [ 1.          0.69108951  0.46134246]
 [ 1.          0.91427779  0.90250374]
 [ 1.          0.41315088  0.96343909]
 [ 1.          0.37413265  0.16922842]
 [ 1.          0.46084659  0.09903664]
 [ 1.          0.84266849  0.08942897]
 [ 1.          0.86850117  0.96394937]
 [ 1.          0.73954752  0.14138912]
 [ 1.          0.14772535  0.28592079]
 [ 1.          0.00865275  0.71371016]
 [ 1.          0.3414815   0.52940503]
 [ 1.          0.88910397  0.09337233]
 [ 1.          0.42716407  0.67952783]
 [ 1.          0.66483356  0.62616943]
 [ 1.          0.81675031  0.74831375]
 [ 1.          0.66952455  0.25077261]
 [ 1.          0.17366785  0.66831817]

* Desarrolla una función `discriminante_lineal` tal que reciba tres valores `k_0` `k_1` y `k_2` y  una matriz `X` de    2 por `N` y devuelva un vector `Y` de `N` elementos tales que por cada renglon `j` de la matriz X, se devuelva el 
   `j`-ésimo valor del vector `Y` tal que su valor sea `sign(k_0 + k_1 * x_1 + k_2 * x_2)`.
   ```
   Y = discriminante_lineal(k_0, k_1, k_2, X) 
   ``` 

In [14]:
def discriminante_lineal(k_0, k_1, k_2, X):

    Y = []

    for i in xrange(X.shape[0]):
        x_1 = X[i][1]
        x_2 = X[i][2]
        Y.append(np.sign(k_0 + k_1 * x_1 + k_2 * x_2))

    return Y

In [121]:
print "Funcion 3: discriminante_lineal"

Y = discriminante_lineal(k_0, k_1, k_2, X)

print Y

Funcion 3: discriminante_lineal
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


* Desarrolla una función `PLA` que implemente el algoritmo de aprendizaje del perceptrón para encontrar 
   `w_0`, `w_1` y `w_2`.
   ```
   w_0, w_1, w_2 = PLA(X, Y)
   ```

In [122]:
def PLA(X, Y):

    max_iter = 0
    w = np.random.uniform(0, 1, size=X.shape[1])
    Ye = np.sign(np.dot(X, w)) 
    error = Ye * Y
    
    while any(e != 1 for e in error) and max_iter < 1000:
        i = np.random.choice(X.shape[0])
        sign = np.sign(np.dot(X[i], w))

        if sign == Y[i]:
            pass
        else:
            w = w + np.dot(X[i], Y[i])
            Ye = np.sign(np.dot(X, w)) 
            error = Ye * Y

        max_iter += 1

    return w

In [123]:
print "Funcion 4: PLA"
w_0, w_1, w_2 = PLA(X, Y)
print w_0
print w_1
print w_2

Funcion 4: PLA
0.0515851262963
0.255149055805
0.428145195


* Desarrolla una función `error_clasificacion` que reciba un vector de valores `Y`y un vector de valores `Y_e` y 
   calcule el porcentaje de valores diferentes entre ambos vectores
   ```
   e = error_clasificacion(Y, Y_e)
   ```

In [124]:
def error_clasificacion(Y, Y_e):

    c = 0

    for i in xrange(len(Y)):
        if Y[i] != Y_e[i]:
            c += 1

    return c / float(len(Y))

In [125]:
print "Funcion 5: error_clasificacion"
E_i = error_clasificacion(Y, Y)
print E_i

Funcion 5: error_clasificacion
0.0


* Prueba que el conjunto funciona, esto es, para diferentes valores de `N` y repetidos tantas veces 
   como sea necesario al realizar lo siguiente:
   ```
   k_0, k_1, k_2 = modelo_aleatorio()
   X = genera_datos(N)
   Y = discriminante_lineal(k_0, k_1, k_2, X)
   w_0, w_1, w_2 = PLA(X, Y)
   Y_e = discriminante_lineal(w_0, w_1, w_2, X)
   E_i = error_clasificacion(Y, Y_e)
   ```
   en todos los casos `e` debe de ser 0 o un valor muy cercano (como `1e-12`).

In [129]:
print "Funcion 6: prueba E_i"
k_0, k_1, k_2 = modelo_aleatorio()
X = genera_datos(10000)
Y = discriminante_lineal(k_0, k_1, k_2, X)
print Y
w_0, w_1, w_2 = PLA(X, Y)
Y_e = discriminante_lineal(w_0, w_1, w_2, X)
E_i = error_clasificacion(Y, Y_e)
print E_i

Funcion 6: prueba E_i
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.

* `E_i` Es en este caso el error en muestra, que es el que se obtiene de verificar el error que el clasificador
   (descrito por `w_0`, `w_1` y `w_2`) presenta respecto a los datos reales, pero únicamente de datos de aprendizaje.
   
   Este error no es exactamente el error fuera de muestra, y para calcular dicho error en el plano [0, 1] x [0, 1]
   hay que realizar algunas operaciones de geometría analítica que no siempre son sencillas. Por esta razón vamos a
   considerar estimar el E_out, con un conjunto de datos sensiblemente mayor al que utilizamos para el aprendizaje.
   por ejemplo:
   ```
   X_o = genera_datos(10000)
   Y_o = discriminante_lineal(k_0, k_1, k_2, X_o)
   Y_eo = discriminante_lineal(w_0, w_1, w_2, X_o)
   E_o = error_clasificacion(Y_o, Y_eo)
   ```

In [130]:
print "Funcion 7: prueba E_o"
X_o = genera_datos(10000)
Y_o = discriminante_lineal(k_0, k_1, k_2, X_o)
Y_eo = discriminante_lineal(w_0, w_1, w_2, X_o)
E_o = error_clasificacion(Y_o, Y_eo)
print E_o

Funcion 7: prueba E_o
0.0


* Ahora vamos a comparar con un número diferente de datos de aprendizaje, como E_o cambia en terminos generales. 
   Con el fin de generalizar, haga una función que reciba un valor `N` y devuelva un `E_o_prom` estimado de la 
   siguiente forma:
   ```
   Entrada: N
   Salida: E_o_prom
   
   E_lista = arreglo e numeros de 500 espacios
   X_o = genera_datos(10000)

   para epoch de 1 a 100:
      k_0, k_1, k_2 = modelo_aleatorio()
      Y_o = discriminante_lineal(k_0, k_1, k_2, X_o)

      para iter de 1 a 100:
          X = genera_datos(N)
          Y = discriminante_lineal(k_0, k_1, k_2, X)
          w_0, w_1, w_2 = PLA(X, Y)
          Y_eo = discriminante_lineal(w_0, w_1, w_2, X_o)
          E_o = error_clasificacion(Y_o, Y_eo)
          E_lista[100 * epoch + iter] = E_o
      fin para

   fin para

   devuelve el valor promedio de los valores de E_lista
   ```
   Como puede verse en el pseudocódigo, la idea es poder estimar en forma general el error promedio entre el 
   E_i y el E_o que tendríamos si tuvieramos solo `N` datos de aprendizaje. 

In [131]:
def E_o_prom(N):

    E_lista = np.zeros(500)
    X_o = genera_datos(10000)

    for epoch in xrange(1, 100):
        k_0, k_1, k_2 = modelo_aleatorio()
        Y_o = discriminante_lineal(k_0, k_1, k_2, X_o)

        for iter in xrange(1, 100):
            X = genera_datos(N)
            Y = discriminante_lineal(k_0, k_1, k_2, X)
            w_0, w_1, w_2 = PLA(X, Y)
            Y_eo = discriminante_lineal(w_0, w_1, w_2, X_o)
            E_o = error_clasificacion(Y_o, Y_eo)
            indice = 100 * epoch + iter

            if len(E_lista) <= indice:
                temp = np.zeros(indice + 1)
                for i in xrange(0, len(E_lista)):
                    temp[i] = E_lista[i]
                temp[indice] = E_o
                E_lista = temp[:]
            else:
                E_lista[indice] = E_o

    return sum(E_lista) / len(E_lista)

In [132]:
print "Funcion 8: pseudocodigo E_o_prom"
E_o_prom = E_o_prom(5)
print E_o_prom

Funcion 8: pseudocodigo E_o_prom
0.06456966
