# Introducción a Numpy y Matplotlib

## Inicialización de una libreta IP[y]

Para inicializar la libreta y poderla utilizar con mumpy y matplotlib, y asegurarse que los gráficos se presenten donde deben de estar es necesario ejecutar las siguientes instrucciones:

In [11]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import random

Ejercicio 1

In [3]:
def modelo_aleatorio():
    x1, x2, y1, y2 = np.random.rand(4)
    k_2 = 1
    k_1 = (y2 - y1) / (x2 - x1) 
    k_0 = y1 - k_1 * x1
    
    return k_0, k_1, k_2

Ejercicio 2

In [10]:
def genera_datos(N):
    matriz = np.random.rand(N, 3)
    for i in range(N):
        matriz[i][0] = 1
    return matriz

[[ 1.          0.2027052   0.46060543]
 [ 1.          0.4633462   0.52576422]
 [ 1.          0.08478762  0.6703465 ]
 [ 1.          0.86316402  0.95010997]]


Ejercicio 3

In [ ]:
def discriminante_lineal(k_0, k_1, K_2, X):
    Y = np.ones(X.shape[0])
    for i in xrange(X.shape[0]):
        Y[i] = np.sign(k_0 + k_1 * X[i][0] + k_2 * X[i][1])

    return Y

Ejercicio 4

In [ ]:
def PLA(X,Y):
    w = np.ones(3)
    ind = np.arange(0, X.shape[0])
    while True:
        np.random.shuffle(ind)
        flag = True
        for i in ind:
            y_e = np.sign(np.dot(X[i],w))
            if (Y[i] != y_e):
                w = w + np.dot(X[i], Y[i])
                flag = False
                break
        if flag:
            break
    return w

Ejercicio 5

In [ ]:
def error_clasificacion(Y, Y_e):
    e = 0
    for i in range(len(Y)):
        if Y[i] != Y_e[i]:
            e += 1
    return 1.0*e/len(Y)

Ejercicio 6

In [1]:
k_0, k_1, k_2 = modelo_aleatorio()
X = genera_datos(10)
Y = discriminante_lineal(k_0, k_1, k_2, X)
w_0, w_1, w_2 = PLA(X, Y)
Y_e = discriminante_lineal(w_0, w_1, w_2, X)
E_i = error_clasificacion(Y, Y_e)

NameError: name 'modelo_aleatorio' is not defined

Ejercicio 7

In [ ]:
X_o = genera_datos(10000)
Y_o = discriminante_lineal(k_0, k_1, k_2, X_o)
Y_eo = discriminante_lineal(w_0, w_1, w_2, X_o)
E_o = error_clasificacion(Y_o, Y_eo)

Ejercicio 8

In [ ]:
def eout_p(N):
    E_lista = np.zeros(500)
    X_o = genera_datos(10000)

    for epoch in range(1, 101):
        k_0, k_1, k_2 = modelo_aleatorio()
        Y_o = discriminante_lineal(k_0, k_1, k_2, X_o)

        for iter in range(1, 101):
            X = genera_datos(N)
            Y = discriminante_lineal(k_0, k_1, k_2, X)
            w_0, w_1, w_2 = PLA(X, Y)
            Y_eo = discriminante_lineal(w_0, w_1, w_2, X_o)
            E_o = error_clasificacion(Y_o, Y_eo)
            
            i = 100 * epoch + iter
            if i < 500:
                E_lista[i] = E_o
            
    return 1.0*E_lista.sum()/500

print eout_p(2)