In [8]:
#k_2 = 1 k_1 = (y2 - y1) / (x2 - x1) k_0 = y_1 - k_1 * x_1
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

def modelo_aleatorio():
    array = np.random.rand(1,4)
    x1 = array[0][0]
    y1 = array[0][1]
    x2 = array[0][2]
    y2 = array[0][3]
    
    k2 = 1
    k1 = (y2-y1)/(x2-x1)
    k0 = y1-k1*x1
    
    return k0,k1,k2

def genera_datos(N):
    return None if N <= 0 else np.column_stack((np.ones(N), (np.random.uniform(0, 1, size=(N, 2)))))

def discriminante_lineal(k0,k1,k2,x):
    Y = []
    for i in xrange(x.shape[0]):
        x1=x[i][0]
        x2=x[i][1]
        Y.append(np.sign(k0+k1*x1+k2*x2))
    return Y




def PLA(X, Y):
    max_iter = 0
    w = np.random.uniform(0, 1, size=X.shape[1])
    Ye = np.sign(np.dot(X, w)) 
    error = Ye * Y
    
    while any(e != 1 for e in error) and max_iter < 1000:
        i = np.random.choice(X.shape[0])
        sign = np.sign(np.dot(X[i], w))

        if sign == Y[i]:
            pass
        else:
            w = w + np.dot(X[i], Y[i])
            Ye = np.sign(np.dot(X, w)) 
            error = Ye * Y

        max_iter += 1

    return w

def error_clacificacion(Y,Ye):    
    var = 0
    for i in xrange(len(Y)):
        var += Y[i]-Ye[i]       
    return var/len(y)


k_0, k_1, k_2 = modelo_aleatorio()
print "modelo aleatorio"
print k_0
print k_1
print k_2
print ""

print "Generar datos"
x = genera_datos(25)
print x
print ""

print "discriminante lineal"
y = discriminante_lineal(k_0,k_1,k_2,x)
print y
print ""

print "PLA:"
w=PLA(x,y)
print "w1,w2,w3"
print w

print "error de calcificacion"
print error_clacificacion(w,y)


#Entrada: N
#Salida: E_o_prom
def Eo_prom(N):    
    E_lista = [0]*500
    X_o = genera_datos(500)
    
    
    for epoch in range(0,100):
        k_0, k_1, k_2 = modelo_aleatorio()
        Y_o = discriminante_lineal(k_0, k_1, k_2, X_o)
        
        for iter in range(0,100):
            X = genera_datos(N)
            Y = discriminante_lineal(k_0, k_1, k_2, X)
            w_0, w_1, w_2 = PLA(X, Y)
            Y_eo = discriminante_lineal(w_0, w_1, w_2, X_o)
            E_o = error_clacificacion(Y_o, Y_eo)
            indice = 100 * epoch + iter
            
           
            if len(E_lista) <= indice:
                temp = np.zeros(indice + 1)
                for i in xrange(0, len(E_lista)):
                    temp[i] = E_lista[i]
                temp[indice] = E_o
                E_lista = temp[:]
            else:
                E_lista[indice] = E_o

    return sum(E_lista) / len(E_lista)

print "funcion"
print Eo_prom(5)

modelo aleatorio
-2.32441912136
4.33109041798
1

Generar datos
[[ 1.          0.37644168  0.29988929]
 [ 1.          0.92053994  0.44643733]
 [ 1.          0.76154696  0.88549941]
 [ 1.          0.02533237  0.08036144]
 [ 1.          0.3233881   0.05960549]
 [ 1.          0.79905463  0.31895815]
 [ 1.          0.18174486  0.19651559]
 [ 1.          0.8146073   0.5505029 ]
 [ 1.          0.25530116  0.80264033]
 [ 1.          0.56002027  0.71710908]
 [ 1.          0.1745125   0.51929143]
 [ 1.          0.69720182  0.32254864]
 [ 1.          0.1394798   0.02104484]
 [ 1.          0.95532651  0.97779758]
 [ 1.          0.86649852  0.40656603]
 [ 1.          0.79617599  0.41575652]
 [ 1.          0.83006704  0.29042186]
 [ 1.          0.0099008   0.91206016]
 [ 1.          0.15748526  0.48753047]
 [ 1.          0.51795017  0.90401855]
 [ 1.          0.88046177  0.67317346]
 [ 1.          0.51566894  0.64587532]
 [ 1.          0.95814977  0.23391319]
 [ 1.          0.40595461  0.56793324]
 